### ISSUE TITLE
A.08.IR222.TGR8.linktoOpenSearchDescription

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/download-service#56] opened 2016-03-23 10:12 UTC
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

How is this different from A.04.TGR4.conformtoOpenSearch1.1?
# Proposed Change

Drop one test.

**Comment by thijsbrentjens** [comment] 2016-04-01 15:16
The difference is that this ATS tests for the existence of the link in the ATOM feed. The second bullet, on testing if the document is a "valid OpenSearch Document" is somehow a duplicate of A.04.TGR4.conformtoOpenSearch1.1. 

Proposal: remove the word "valid" in the second test step and refer to A.04.TGR4.conformtoOpenSearch1.1 for testing OpenSearch conformance.

**Comment by thijsbrentjens** [comment] 2016-04-08 14:59
No comments received. Accept proposal.

**Closed as completed** 2016-08-01 16:10 UTC
Labels: type:GE, comm:ARE3NA, sev:medium, status:implemented, res:accepted-with-modifications
